### ISSUE TITLE
Problemi su interfaccia utente client

### ISSUE THREAD

**Issue by luca-lezzerini** [nicoloabatecola/KeZapp#2]
L'interfaccia non rispetta il progetto:

1) Manca la label sul pulsante registrazione
2) Si suggerisce di creare due div, una per il gruppo registrazione e una per il resto, con ngIf che mostri solo uno dei due in base al codice sessione memorizzato sul client: se undefined/null mostra solo la registrazione, altrimenti solo la parte sotto la registrazione.

**Comment by capponiFelice92** [comment]
commit 65f55016f037cc73cd429fd0633617e4ff6fece2
Create div con *ngIf che mostrano solo il blocco di registrazione se sessione, se sessione non è nulla viene visualizzato tutto il resto e nascosto il blocco di registrazione, ancora non abbiamo creato il dto
