### ISSUE TITLE
logica caso d'uso registrazione:

### ISSUE THREAD

**Issue by capponiFelice92** [nicoloabatecola/KeZapp#3]
Il codice univoco generato per identificare un utente dopo una registrazione fa parte solo della singola run, non avendo una pagina di login?

es: mi registro con nickname Felice92, il server mi da un identificativo 13452, non prevedendo un caso d'uso di login, anche se l'utente tramite client ricordasse il suo identificativo, ed esso fosse salvato e accomunato ad un nickname nel DB, non sarebbe comunque in grado di rientrare con la prima registrazione effettuata.

per cui ogni singola run della app i vari utenti dovranno effettuare la registrazione ?
E' questa la logica della registrazione?

**Comment by luca-lezzerini** [comment]
Sì, esatto

**Comment by capponiFelice92** [comment]
perfetto grazie
