### ISSUE TITLE
come si aggiorna un record con query hibernate?

### ISSUE THREAD

**Issue by capponiFelice92** [nicoloabatecola/KeZapp#4]

**Comment by capponiFelice92** [comment]
![Uploading kezapp-server-his - Apache NetBeans IDE 12.2 03_03_2021 09_19_39.png…]()

**Comment by luca-lezzerini** [comment]
Usi il metodo save: inserisce e aggiorna, vede se la chiave è null oppure no per decidere se inserire o aggiornare
