### ISSUE TITLE
dubbi su cosa devono contenere le proprietà aliasDestinatario e aliasMittente

### ISSUE THREAD

**Issue by capponiFelice92** [nicoloabatecola/KeZapp#5]
Quando viene mandato un messaggio, viene spedito un inviaMessaggioDto dal client con una post, il server ritorna con un RegistrazioneDto, in quanto contiene proprietà in grado di ospitare le liste di Chat e liste di Messaggio.

Salvando il messaggio su Db, come aliasMittente bisogna inserire nickname o sessione?
Quando voglio mandare un messaggio a un Utente specifico, devo accomunarlo a un messaggio con la sessione o con il nickname dell'account?

**Comment by luca-lezzerini** [comment]
Nickname in entrambi i casi
